

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: banco
    ports:
      - "3306:3306"
    volumes:
      - meu_login_mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  backend:
    build:
      context: .  
      dockerfile: Dockerfile.backend
    environment:
      MYSQL_HOST: meu_login-mysql-1
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: banco
    ports:
      - "3001:3001"
    depends_on:
      - mysql

    networks:
      - app_network

  frontend:
    build:
      context: ./  # O diretório do frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # A porta onde o frontend estará disponível
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    
volumes:
  meu_login_mysql_data:
    driver: local
